[Reviewer: Graeme] Wildcard IMPU stress testing
Metaswitch/clearwater-perf-utils pull request #25
Opened 2017-03-06 11:04 UTC by rkd-msw

wildcard_caller.xml is just caller.xml with a P-Profile-Key.

2017-03-13 13:58 UTC, graemerobertson requested changes
Pretty good, apart from the fact that it all looked rubbish to me

2017-03-13 13:58 UTC, graemerobertson commented on clearwater-sip-stress-coreonly.root/usr/share/clearwater/bin/run_stress
> +        register_csv.write("{}{}000\n".format(s, WILDCARD_DELIMITER))
No?

2017-03-13 13:58 UTC, graemerobertson commented on clearwater-sip-stress-coreonly.root/usr/share/clearwater/bin/run_stress
> +    caller_file = "caller.xml"
Is this supposed to be `wildcard_caller.xml`?!

2017-03-13 13:58 UTC, graemerobertson commented on clearwater-sip-stress-coreonly.root/usr/share/clearwater/bin/run_stress
> +    callee_file = "wildcard_callee.xml"
And where is `wildcard_callee.xml`?

2017-03-13 13:58 UTC, graemerobertson commented on clearwater-sip-stress-coreonly.root/usr/share/clearwater/bin/run_stress
> +    caller_file = "caller.xml"
Do we actually need `wildcard_caller.xml`? Is it not the same, but with a P-Profile-Key? Can't we just have [field4] as `P-Profile-Key: <blah>\n` or whatever and use the same file?

2017-03-13 14:04 UTC, graemerobertson commented on clearwater-sip-stress-coreonly.root/usr/share/clearwater/bin/run_stress
> +        register_csv.write("{}{}000\n".format(s, WILDCARD_DELIMITER))
Ah, I think I understand this now (having seen the Husk changes) - worth a comment?

2017-03-21 10:25 UTC, rkd-msw commented on clearwater-sip-stress-coreonly.root/usr/share/clearwater/bin/run_stress
> +        register_csv.write("{}{}000\n".format(s, WILDCARD_DELIMITER))
Yep, comment updated.

2017-03-21 10:25 UTC, rkd-msw commented on clearwater-sip-stress-coreonly.root/usr/share/clearwater/bin/run_stress
> +    caller_file = "caller.xml"
Good idea - done.

2017-03-21 10:27 UTC, rkd-msw commented on clearwater-sip-stress-coreonly.root/usr/share/clearwater/bin/run_stress
> +    callee_file = "wildcard_callee.xml"
Yes - I mixed up caller and callee here.

2017-04-03 08:47 UTC, merged